### ISSUE TITLE
Add Chrome on Android to supported platforms

### ISSUE THREAD

**Issue by bshanks** [ehmicky/cross-platform-terminal-characters#1]
Thanks for making this. Scrolling thru the README.md on Github on a Chrome browser on Android (Chrome version 89.0.4389.105, Android 11 Build RQA.210305.006), I noticed that some characters weren't visible (were replaced by little rectangles). The following should be enough information to amend the README to include this platform (by removing these non-visible characters). The characters that are currently not visible in the README.md viewed on Github with a Chrome browser on Android are:

- Box drawing: 203e, 2043, 257a, 257c, 257e, 205e
- Geometric shapes: 2024, 2219, 25e6
- Punctuation: 203d, 201f, 2e17
- Numbers and math: 2153 thru 215a, 2070, 2071, 2074 thru 207e (207f was fine though), 2080 thru 2089, 2090 thru 2094, 208a thru 208e
- Other symbols: 2117, 2132, 214d, 214e, 2183, 2184, 20a0 thru 20a2, 20a5, 20a6, 20a8 thru 20aa, 20ad thru 20ba, 20bd, 20bf, 0e3f
  - (in other words, the only "other symbols" visible were: 2020, 2021, 263a thru 263c, 2736, 2640, 2642, 2660, 2663, 2665, 2666, 266a, 266b, 266f, 2105, 2113, 2116, 2122, 2126, 212e, 20a3, 20a4, 20a7, 20ab, 20ac)
- Miscellaneous: none of the symbols were visible, except for the following visible ones: fb00 thru fb04, fb31 thru fb17

The ones in the README yet not in the list above were all visible. The non-control characters linked to from the ASCII and Western languages sections were all visible.

**Comment by ehmicky** [comment]
Hi @bshanks, thanks for your input!

This list of only for terminal applications, not GUI applications.

I have added https://github.com/ehmicky/cross-platform-terminal-characters/commit/1c7816164d3d4b0698d89d25f61ba0582c17cbb9 to make this more clear.

**Comment by bshanks** [comment]
OK thanks! Please ignore my pull request then.

**Comment by ehmicky** [comment]
However, if you find any character that does not display correctly in your terminal, please feel free to let me know!

**Comment by bshanks** [comment]
Will do, thanks

**Comment by ehmicky** [comment]
@all-contributors Please add @bshanks for his thorough research.

**Comment by ehmicky** [comment]
@all-contributors Please add @bshanks for research

**Comment by ehmicky** [comment]
@all-contributors Please add @bshanks for userTesting

**Comment by bshanks** [comment]
Everything in the README.md is visible on my Gnome terminal on Ubuntu (same versions as you tested).

**Comment by bshanks** [comment]
That's nice of you, thanks! 😊

**Comment by ehmicky** [comment]
Thanks for reporting @bshanks!

Please note there is also a [command line to print all characters](https://github.com/ehmicky/cross-platform-terminal-characters#cli):

```
npx cross-platform-terminal-characters
```

**Comment by bshanks** [comment]
Thanks
